### ISSUE TITLE
Transitions specification

### ISSUE THREAD

**Issue by choisy** [thinhong/denim#1]
To make user interface even smoother, I would not force the user to specify `NULL` values explicitly: whenever a distribution is not specified explicitly, the program has to understand that it's Markovian. I would thus replace
```
distributions <- list(
  S = NULL,
  I = exponential(rate = 0.5),
  R = NULL
)
```
by
```
distributions <- list(I = exponential(rate = 0.5))
```
Furthermore, whenever the elements of `distributions` are all of the same type, I would also allow the user to specify it with a vector instead of a list:
```
distributions <- c(I = exponential(rate = 0.5))
```

**Comment by thinhong** [comment]
I've fixed this
