### ISSUE TITLE
Parameters to define in the README

### ISSUE THREAD

**Issue by choisy** [thinhong/denim#13]
Below the "Simple SIR model" in the README, you list a number of parameters to define but this is not too clear.

* `daysFollowUp`: in what this is different from `simulationDuration`?
* `errorTolerance`: where is this defined?
*  what is the difference between `constant()` and `probability()`

**Comment by choisy** [comment]
OK, now I see about `daysFollowUp` and `errorTolerance`. Anyway, again, the example given in the README should always be the simplest example possible, both in terms of model and in terms of these tuning parameters. Use default values and don't mention them. This level of detail should be reserved to a vignette. This said, I still don't understand the difference between `contant()` and `probability()`.

**Comment by thinhong** [comment]
> OK, now I see about `daysFollowUp` and `errorTolerance`. Anyway, again, the example given in the README should always be the simplest example possible, both in terms of model and in terms of these tuning parameters. Use default values and don't mention them. This level of detail should be reserved to a vignette. This said, I still don't understand the difference between `contant()` and `probability()`.

Actually `daysFollowUp` has been renamed to `simulationDuration` but I forgot to change it in the README. I made `constant()` as number of individuals (not being multiplied to the left compartment, therefore can be > 1, example we can give vaccine to 100 people per day then it is `constant(100)`), while `probability()` is the probability (will be multiplied to the number of people in the left compartment and has value from [0, 1]). Ah, `probability()` is a better name than my current `transprob()`, I will change it.

**Comment by choisy** [comment]
OK, got it, all clear now, thanks.
