### ISSUE TITLE
Error in the second example of the README

### ISSUE THREAD

**Issue by choisy** [thinhong/denim#17]
When I run
```
> fmod <- sim(daysFollowUp = 20, errorTolerance = 0.01, 
+             timeStep = 0.001,
+             transitions = transitions,
+             initialValues = initialValues, parameters = parameters)
```
(second example of the README), I guess this error message:
```
Error in sim(daysFollowUp = 20, errorTolerance = 0.01, timeStep = 0.001,  : 
  unused argument (daysFollowUp = 20)
```

**Comment by thinhong** [comment]
> When I run
> 
> ```
> > fmod <- sim(daysFollowUp = 20, errorTolerance = 0.01, 
> +             timeStep = 0.001,
> +             transitions = transitions,
> +             initialValues = initialValues, parameters = parameters)
> ```
> 
> (second example of the README), I guess this error message:
> 
> ```
> Error in sim(daysFollowUp = 20, errorTolerance = 0.01, timeStep = 0.001,  : 
>   unused argument (daysFollowUp = 20)
> ```

Sorry, please change the `daysFollowUp` argument to `simulationDuration` and it will work

**Comment by choisy** [comment]
Indeed.
