### ISSUE TITLE
Interface of runSim()

### ISSUE THREAD

**Issue by choisy** [thinhong/denim#3]
I'm surprised to see `transmissionRate = 4`, `infectiousComps = "I"` in the call of `sunSim()`. Do we really need to specify this here? If yes why? Can't we instead merge `transitions` and `distributions` into one `transitions` vector such as:
```
transitions <- c(
  "S -> E" = beta * S * I / N,
  "E -> I" = weibull(scale = sigma_scale, shape = sigma_shape),
  "I -> R" = gamma
)
```
Then we'd have a named `parameters` vector defining the values of the parameters of the transitions vector.

**Comment by thinhong** [comment]
I've fixed this
